import re

name = str(input("输入文件名："))

f = open("./"+name,"r",encoding='utf-8')
code = f.read()
f.close()
def is_contain_chinese(check_str):
    for ch in check_str:
        if u'\u4e00' <= ch <= u'\u9fa5':
            return True
    return False

firstname = name.split(".")[0]
i = 0
out = ""
lan = ""

for line in code.split("\n"):
    tmp = line
    i=i+1
    for xstr in re.compile(r'\'[\u4e00-\u9fa5 %0-9，\(\)a-zA-z0-9,：:_\.\~\-/]*\'').findall(line):
        if is_contain_chinese(xstr):
            print('第'+str(i)+'行: '+xstr)
            tmp = tmp.replace(xstr,firstname+"_line_"+str(i))
            lan = lan+"var "+firstname+"_line_"+str(i)+" = \""+xstr[1:-1]+"\"\n"
    for xstr in re.compile(r'\"[\u4e00-\u9fa5 %0-9，\(\)a-zA-z0-9,：:_\.\~\-/]*\"').findall(line):
        if is_contain_chinese(xstr):
            print('第'+str(i)+'行: '+xstr)
            tmp = tmp.replace(xstr,firstname+"_line_"+str(i))
            lan = lan+"var "+firstname+"_line_"+str(i)+" = \""+xstr[1:-1]+"\"\n"
    out = out+tmp+"\n"

f = open("./"+name,"w",encoding='utf-8')
f.write(out)
f.close()

f = open("./language.js","a+",encoding='utf-8')
f.write("//"+name+" update at 2020/5/6 \n//generated by python reMoudle\n")
f.write(lan)
f.close()
print(lan)